name: dating_app_flutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  #Firebase
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.3.4
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  #Design
  google_fonts: ^6.2.1

  #Tools/Utils
  geolocator: ^13.0.2
  workmanager: ^0.5.2
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  google_maps_flutter: ^2.1.3
  rive: ^0.13.20

  geoserviceplugin:
    path: ../geoserviceplugin_flutter

  logger: ^2.5.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  image_cropper: ^9.0.0
  intl: ^0.19.0

  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/logo_300.png
    - assets/icons/pin.svg
    - assets/icons/pin.png
    - assets/icons/logo.svg
    - assets/icons/google_logo_white.png
    - assets/icons/apple_logo_black.png
    - assets/icons/apple_logo_white.png
    - assets/icons/logo_animation.riv
    - assets/images/default_profile_picture.png
    - assets/images/leon.jpg
